Fix the last commit; compression was being enabled on mac native which led to
ERROR: test_auxv_chunked_reads_work_debugserver (tools/lldb-server/TestGdbRemoteAuxvSupport.py)
ERROR: test_auxv_data_is_correct_size_debugserver (tools/lldb-server/TestGdbRemoteAuxvSupport.py)
ERROR: test_auxv_keys_look_valid_debugserver (tools/lldb-server/TestGdbRemoteAuxvSupport.py)
ERROR: test_qSupported_returns_known_stub_features_debugserver (tools/lldb-server/TestLldbGdbServer.py)

failures because debugserver was advertising compression being available, e.g.

send packet: $qSupported:xmlRegisters=i386,arm,mips#12
read packet: $qXfer:features:read+;PacketSize=20000;qEcho+;SupportedCompressions=zlib-deflate;DefaultCompressionMinSize=384#00

maybe these tests should be a little more accepting of additional
features.  but I didn't mean for this to be enabled on mac native.

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@292890 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit bf8d31f833d807ce3fa1fa0bebf21a25014db34e)

apple-llvm-split-commit: 2bc6e92bc03b7029814ad00eb8d29b8ebff8a109
apple-llvm-split-dir: lldb/