[unittest] Fix missing user-provided default constructor
error: default initialization of an object of const type 'const Pod'
without a user-provided default constructor

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@354602 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit 30ca75512100625a324e5e5c5ab3cb0318371b05)

apple-llvm-split-commit: 6db0c32bc7fbaf165f9e7fe8e478865ff962cea3
apple-llvm-split-dir: lldb/