[ObjectFileMachO] Revert std::make_shared
This caused a rather interesting error message on MSVC: error C2338 and
I'm not sure how to properly fix it.

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@353769 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit 44e6b4e62527a51a781112178b88d74de4eabd6a)

apple-llvm-split-commit: 02f9154164bfe9dc77ea61326a33e928f79485f8
apple-llvm-split-dir: lldb/